version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: incrediblyhardtoguess
      POSTGRES_DB: pidun
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: